### ISSUE TITLE
Irresponsive Paragraph

### ISSUE THREAD

**Issue by HanzCEO** [GodotID/website#10]
![Screenshot_2023-02-02-20-47-06-765_com android chrome](https://user-images.githubusercontent.com/40712686/216342256-0d9ae038-34bf-4714-82a0-1c5ad53984d6.jpg)

Please solve this, good luck.

**Comment by codewithbharat** [comment]
hey! @HanzCEO  Assign me this task I would like to work on this issue...

**Comment by HanzCEO** [comment]
I have assigned you to this issue. Please work on this issue for the next 2 days. If you're not done, the work will be salvaged.

Thank you

**Comment by HanzCEO** [comment]
@codewithbharat, your time is up.
