### ISSUE TITLE
Redirect Jams to Itch.io

### ISSUE THREAD

**Issue by HanzCEO** [GodotID/website#2]
![image](https://user-images.githubusercontent.com/40712686/175778326-51722622-1b23-48fe-9681-a206e436293a.png)
There is this link on our website header.

Don't overwrite the link inside `<a>`
But create the `/jams` path and redirect visitor to this URL: https://itch.io/jams/hosted-by-hanzhaxors

You can use javascript,
Thank you

**Comment by AMMAR-62** [comment]
Hey! I would like to take up this issue, I would like to use react-router-dom@6 package and embed the Routes in app.tsx, should I go ahead ... react with 👍

**Comment by HanzCEO** [comment]
@AMMAR-62 If you can't proceed, i would like to label this issue as salvageable.

**Comment by AMMAR-62** [comment]
Hey! I would like to commit to this issue, i'll submit the PR by EOD, if it's okay??

**Comment by HanzCEO** [comment]
It's okay bud.

**Comment by AMMAR-62** [comment]
Hey! I sent a PR #5, for issue #2, check for file changes and recommend additional changes if needed🙏

**Comment by HanzCEO** [comment]
> Hey! I sent a PR #5, for issue #2, check for file changes and recommend additional changes if needed🙏

Thank you! going after it right now

**Comment by HanzCEO** [comment]
This issue is salvageable. If anybody wants to take the work, let me know by giving your comment here!

**Comment by bluespada** [comment]
> This issue is salvageable. If anybody wants to take the work, let me know by giving your comment here!

just create a new page and redirect to given link ?

**Comment by HanzCEO** [comment]
> > This issue is salvageable. If anybody wants to take the work, let me know by giving your comment here!
> 
> just create a new page and redirect to given link ?

You're right it is exactly like that

**Comment by bluespada** [comment]
> > > This issue is salvageable. If anybody wants to take the work, let me know by giving your comment here!
> > 
> > 
> > just create a new page and redirect to given link ?
> 
> You're right it is 

> > > This issue is salvageable. If anybody wants to take the work, let me know by giving your comment here!
> > 
> > 
> > just create a new page and redirect to given link ?
> 
> You're right it is exactly like that

 I hope PR [#6](https://github.com/GodotID/website/pull/6) solve this issue.
